# Generated by Django 3.2.9 on 2022-04-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=30)),
                ('purchase_price', models.CharField(max_length=15)),
                ('quantity', models.CharField(max_length=15)),
                ('selling_price', models.CharField(max_length=15)),
            ],
        ),
    ]
